---
#- name: Generate user-data.yaml cloud-init vars_file
#  template:
#    src: user-data.yaml.j2
#    dest: "{{ cte_user_dir }}/lxc_user-data.yaml"
#    mode: 0640
#  vars:
#    ssh_keys:
#      - "{{ lookup('file', user.ssh.pubkeyfiles.rsa) }}"
#      - "{{ lookup('file', user.ssh.pubkeyfiles.ecdsa) }}"
#    gecos: "{{ ansible_user_gecos.split(',')[0] }}"
#  tags:
#    - cte-common
#    - cte-cloud-init

- name: Ensure ipv4 forwarding is permanently enabled
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#?net.ipv4.ip_forward.*'
    line: net.ipv4.ip_forward = 1
  become: yes
  notify: "Parse sysctl changes"
  when: ansible_system == "Linux"
  tags:
    - cte-common

- name: Install common packages for CTE use
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3
    - python-netaddr
    - zfsutils-linux
    - npm
    - nodejs
    - tmux
    - vim
    - iptables-persistent
  become: yes
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - cte-common

# Add cte-admin user
- name: Add cte-admin user account
  user:
    name: cte-admin
    shell: /bin/bash
    groups: sudo
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    expires: -1
    create_home: yes
    password: $6$D.RiZA2vcbYDUDtl$zAZBdMFUsyCSna/gnx27SB6Nd4iJZcbIOH.y4AS92nrOVkbYLGSs2qRaJ0bIU9aJq167urTEtOb0w6QWl53u5/
  become: yes

- name: Set cte-admin sudoers privileges
  copy:
    src: cte-admin
    dest: /etc/sudoers.d/cte-admin
    owner: root
    group: root
    mode: '0440'
  become: yes

- name: Set {{ ansible_user_id }} sudoers privileges
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/{{ ansible_user_id }}
    owner: root
    group: root
    mode: '0440'
  become: yes
  vars:
    user_name: "{{ ansible_user_id }}"

#- name: Enable ipv4 forwarding for this session
#  command: sysctl -w net.ipv4.ip_forward=1
#  when: ansible_system == "Linux"
