cte:
  netsec:
    networks:
      public: &pub
        name: 'cte-netsec'
        net: '10.240.243.0/24'
        gateway: '10.240.243.1'
        address: '10.240.243.1/24'
        domain: netsec.cte
    containers:
      - name: netsec-ca1
        course: netsec
        groups: [cte,netsec]
        nics:
          - parent: *pub
            ipv4: '10.240.243.51/24'
      - name: netsec-www
        course: netsec
        groups: [cte,netsec]
        nics:
          - parent: *pub
            ipv4: '10.240.243.52/24'
#      - name: netsec-db
#        course: netsec
#        groups: [cte,netsec]
#        nics:
#          - parent: *pub
#            ipv4: '10.240.243.53/24'
#      - name: netsec-mq
#        course: netsec
#        groups: [cte,netsec]
#        nics:
#          - parent: *pub
#            ipv4: '10.240.243.54/24'
