---
rsa_key_path: "{{ ansible_user_dir }}/.ssh/id_rsa"
ecdsa_key_path: "{{ ansible_user_dir }}/.ssh/id_ecdsa"
vm_os_version: eoan
vm_name: tpd-{{ ansible_user_id }}
vm_packages:
  - npm
  - nodejs
  - tmux
  - vim
  - nginx-core
  - php
  - php-fpm
  - php-mysql
  - php-markdown
  - php-amqp
  - mysql-server
  - rabbitmq-server
