---

- name: Get ovs bridge interfaces names
  shell: ovs-vsctl show | grep -oP '^\s+Bridge\s+\"?\K([^\s\"]+)'
  become: yes
  register: openvswitch_bridges
  ignore_errors: false
  changed_when: false
  check_mode: false

#- name: Show openvswitch bridges
#  debug:
#    msg: "{{ item }}"
#    verbosity: 1
#  loop: "{{ openvswitch_bridges.stdout_lines }}"

- name: Include configure ovs-vlan bridge tasks
  include_tasks: configure_ovs_vlan_bridge.yaml
