---
- name: Remove deprecated packages
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - lxd
    - lxc
  become: yes

- name: Install apt packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - snapd
    - zfsutils-linux
  become: yes

- name: Install lxd snap package
  snap:
    name: "{{ item }}"
    state: present
    classic: yes
  with_items:
    - lxd
  become: yes
