---
- name: Remove deprecated packages
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - lxd
    - lxc
  become: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install apt packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - snapd
    - zfsutils-linux
  become: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install lxd snap package
  snap:
    name: "{{ item }}"
    state: present
    classic: yes
  with_items:
    - lxd
  become: yes

- name: Check ZFS Pool
  command: zpool list -H default
  become: yes
  register: zpool
  ignore_errors: true
  changed_when: zpool.rc == 1
  notify: Initialize LXD
  check_mode: false
