---
#- name: Debug network vars
#  debug:
#    msg: "{{ network.value | from_yaml }}"

#- name: Debug template
#  debug:
#    msg: "{{ lookup('template', 'network_options.j2') | from_yaml }}"

- name: "Setup network"
  command:
    cmd: |
      lxc network create {{ network.value.name }}
      {{ lookup('template', 'network_options.j2') }}
  become: yes
  when: ansible_system == "Linux"
  args:
    creates: /sys/devices/virtual/net/{{ network.value.name }}

- name: Set systemd-resolve domain name
  command:
    cmd: resolvectl domain {{ network.value.name }} {{ network.value.domain }}
  become: yes
  when:
    - ansible_system == "Linux"
    - network.value.domain is defined
  changed_when: false

- name: Check if system supports resolvectl
  stat:
    path: /path/to/something
  register: resolvectl

- name: Set systemd-resolve dns address
  command: "{{ resolvectl.stat.executable | ternary(dns.resolvectl, dns.systemd-resolve) }}"
    cmd:
  become: yes
  when:
    - ansible_system == "Linux"
    - network.value.gateway is defined
  changed_when: false
  vars:
    dns:
      resolvectl: resolvectl dns {{ network.value.name }} {{ network.value.gateway | ipaddr('address') }}
      systemd-resolve: systemd-resolve --set-dns={{ network.value.gateway | ipaddr('address') }} {{ network.value.name }}
