---
#- name: Debug network vars
#  debug:
#    msg: "{{ network.value | from_yaml }}"

#- name: Debug template
#  debug:
#    msg: "{{ lookup('template', 'network_options.j2') | from_yaml }}"

- name: "Setup network"
  command:
    cmd: |
      lxc network create {{ network.value.name }}
      {{ lookup('template', 'network_options.j2') }}
  become: yes
  when: ansible_system == "Linux"
  args:
    creates: /sys/devices/virtual/net/{{ network.value.name }}

- name: Check if system supports resolvectl
  stat:
    path: /usr/bin/resolvectl2
  register: resolvectl
  failed_when: false

- name: Set systemd-resolve dns address
  command:
    cmd: "{{ (resolvectl.stat.exists and resolvectl.stat.executable) | ternary(dns.resolvectl, dns.systemd_resolve) }}"
  become: yes
  when:
    - ansible_system == "Linux"
    - network.value.gateway is defined
  changed_when: false
  vars:
    dns:
      resolvectl: resolvectl dns {{ network.value.name }} {{ network.value.gateway | ipaddr('address') }}
      systemd_resolve: systemd-resolve --set-dns={{ network.value.gateway | ipaddr('address') }} --interface={{ network.value.name }}
