---
#- name: Debug network vars
#  debug:
#    msg: "{{ network.value | from_yaml }}"

#- name: Debug template
#  debug:
#    msg: "{{ lookup('template', 'network_options.j2') | from_yaml }}"

- name: "Setup network"
  command:
    cmd: |
      lxc network create {{ network.value.name }}
      {{ lookup('template', 'network_options.j2') }}
  become: yes
  when: ansible_system == "Linux"
  args:
    creates: /sys/devices/virtual/net/{{ network.value.name }}

- name: Set systemd-resolve domain name
  command:
    cmd: resolvectl domain {{ network.value.name }} {{ network.value.domain }}
  become: yes
  when:
    - ansible_system == "Linux"
    - network.value.domain is defined
  changed_when: false

- name: Set systemd-resolve dns address
  command:
    cmd: resolvectl dns {{ network.value.name }} {{ network.value.gateway | ipaddr('address') }}
  become: yes
  when:
    - ansible_system == "Linux"
    - network.value.gateway is defined
  changed_when: false
