---

- block:

  - name: Install MySQL
    apt:
      name: "{{ package }}"
      state: latest
    loop:
      - python-mysqldb
      - python3-mysqldb
      - mysql-server
    loop_control:
      loop_var: package

  - name: Set the root password
    mysql_user:
      login_user: root
      login_password:  "{{ mysql_root_password }}"
      user: root
      password: "{{ mysql_root_password }}"
      host_all: yes

  - name: Delete anonymous MySQL server user
    mysql_user:
      login_user: root
      login_password:  "{{ mysql_root_password }}"
      user: ''
      host_all: yes
      state: absent

#  - name: Delete anonymous MySQL server user for localhost
#    mysql_user:
#      login_user: root
#      login_password:  "{{ mysql_root_password }}"
#      user: ""
#      state: absent

#  - name: Secures the MySQL root user for IPv6 localhost (::1)
#    mysql_user:
#      login_user: root
#      login_password:  "{{ mysql_root_password }}"
#      user: root
#      password: "{{ mysql_root_password }}"
#      host: "::1"

#  - name: Secures the MySQL root user for IPV4 localhost (127.0.0.1)
#    mysql_user:
#      login_user: root
#      login_password:  "{{ mysql_root_password }}"
#      user: root
#      password: "{{ mysql_root_password }}"
#      host: "127.0.0.1"

#  - name: Secures the MySQL root user for localhost domain (localhost)
#    mysql_user:
#      login_user: root
#      login_password:  "{{ mysql_root_password }}"
#      user: root
#      password: "{{ mysql_root_password }}"
#      host: localhost

#  - name: Secures the MySQL root user for server_hostname domain
#    mysql_user:
#      login_user: root
#      login_password:  "{{ mysql_root_password }}"
#      user: root
#      password: "{{ mysql_root_password }}"
#      host: "{{ ansible_fqdn }}"

  - name: Removes the MySQL test database
    mysql_db:
      login_user: root
      login_password:  "{{ mysql_root_password }}"
      db: test
      state: absent

  - name: Create {{ ansible_user_id }} mysql user
    mysql_user:
      login_user: root
      login_password:  "{{ mysql_root_password }}"
      user: "{{ ansible_user_id }}"
      password: "{{ mysql_root_password }}"
      priv: '*.*:ALL'
      host: localhost
      state: present

  become: yes
  when: ansible_os_family == 'Debian'
  vars:
    mysql_root_password: password
