---
- name: Get hypervisor nodeinfo
  command: virsh nodeinfo
  become: yes
  register: hypervisor_nodeinfo
  ignore_errors: false
  changed_when:
    - hypervisor_nodeinfo.rc == 0
    - hypervisor_nodeinfo.stdout_lines | length > 0
  check_mode: false
  notify:
    - Show hypervisor nodeinfo

- name: Get hypervisor domains
  command: virsh -q list --name --all
  become: yes
  register: hypervisor_domains
  ignore_errors: false
  changed_when:
    - hypervisor_domains.rc == 0
    - hypervisor_domains.stdout_lines | length > 0
  check_mode: false
  notify:
    - Show hypervisor domains
