---
- name: Install openvswitch packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - openvswitch-switch
    - openvswitch-pki
  become: yes
  tags:
    - install_openvswitch  
