---
- name: Install openvswitch packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - openvswitch-switch
    - openvswitch-pki
  become: yes
  tags:
    - install_openvswitch
  when: ansible_facts['os_family'] == "Debian"
