---
- hosts: localhost
  connection: local
  tasks:

    - name: Get network gather network facts
      setup:
        gather_subset:
          - '!all'
          - '!any'
          - network

    - name: Get physical interfaces names
      command: find /sys/class/net -type l -not -lname '*virtual*' -printf '%f\n'
      register: physical_interfaces
      changed_when: false
      check_mode: false

    - name: Get physical interfaces names
      shell: ovs-vsctl show | grep -oP '^\s+Bridge\s+\"?\K([^\s\"]+)'
      become: yes
      register: openvswitch_bridges
      ignore_errors: false
      changed_when: false
      check_mode: false

    - name: Get hypervisor nodeinfo
      command: virsh nodeinfo
      register: hypervisor_nodeinfo
      ignore_errors: false
      changed_when: false
      check_mode: false

    - name: Get hypervisor domains
      command: virsh -q list --name --all
      register: hypervisor_domains
      ignore_errors: false
      changed_when: false
      check_mode: false

    - name: Show physical interfaces
      debug:
        msg: "{{ item }}"
        verbosity: 1
      loop: "{{ physical_interfaces.stdout_lines }}"

    - name: Show openvswitch bridges
      debug:
        msg: "{{ item }}"
        verbosity: 1
      loop: "{{ openvswitch_bridges.stdout_lines }}"

    - name: Show default interface
      debug:
        msg: "Default interface: {{ ansible_default_ipv4.interface }}"
        verbosity: 1

    - name: Show hypervisor nodeinfo
      debug:
        msg: "{{ item }}"
        verbosity: 1
      loop: "{{ hpervisor_nodeinfo.stdout_lines }}"

    - name: Show hypervisor_domains
      debug:
        msg: "{{ item }}"
        verbosity: 1
      loop: "{{ hypervisor_domains.stdout_lines }}"
